### ISSUE TITLE
discovering names service returns error

### ISSUE THREAD

**Issue by ducvan0212** [phylotastic/phylotastic-portal#103]
Discovering names from file service doesnot work. It always return
```"{\"status_code\": 500, \"scientificNames\": []}"```

**Comment by ducvan0212** [comment]
@abusalehmdtayeen

**Comment by ducvan0212** [comment]
I has file GNRS.txt which has content as following:

Aerosakkonema funiforme
Arthrospira jenneri
Arthrospira maxima
Arthrospira platensis
Cephalothrix lacustris
Gloeobacter violaceus
Microcoleus autumnalis
Microcoleus vaginatus
Oxynema thaianum
Phormdium irriguum
Phormidium ambiguum
Phormidium uncinatum
Planktothricoides raciborskii
Planktothrix agardhii
Planktothrix mougeotii
Planktothrix rubescens
Trichodesmium contortum
Trichodesmium erythraeum
Trichodesmium havanum
Trichodesmium hildebrandtii
Trichodesmium tenue
Trichodesmium thiebautii
Tychonema bourrellyi
Tychonema tenue
Wilmottia murrayi

I put it to GNRS and it returned names but your services returned 500 status code instead, @abusalehmdtayeen

**Comment by abusalehmdtayeen** [comment]
@ducvan0212 : Find scientific names from file is a wrapper service of GNRD. If GNRD works, then this service must also work. I think the problem is with the url of the file, not with the service. I created a text file with same content you have, uploaded it into our phylo server and sent the link of the file to the service. It works. You can test using http://phylo.cs.nmsu.edu:5004/phylotastic_ws/fn/names_url?url=http://phylo.cs.nmsu.edu:8080/upload/gnrd_test1.txt 

Please check the url of the file location you are sending to the service.
