### ISSUE TITLE
Some minor issues with the UI

### ISSUE THREAD

**Issue by hlapp** [phylotastic/phylotastic-portal#143]
* [x] “Feedback” menu item goes to FAQ instead of where to give feedback.
* [x] I would acknowledge the NSF grant# under About.
* [x] The “How can I get involved” in the FAQ gives "~~~" as the email address at which to email the project. (And the Gitter URL isn’t hyperlinked.)

**Comment by ducvan0212** [comment]
@arlin Which email address would you like me to add to the placeholder in FAQ page, under "How can I get involved" section?
@hlapp Thank you very much. If there is any other things I can do to improve UI/UX of the portal, please let me know.

**Comment by arlin** [comment]
@ducvan0212 for now let's just use my address, arlin@umd.edu.  

The NSF grant number is 1458572 "Collaborative Research: ABI Development: An open infrastructure to disseminate phylogenetic knowledge"

**Comment by arlin** [comment]
The feedback URL is now bit.ly/phylofeedback as per #153.  

I see that @ducvan0212 has changed the code for the about page to include the NSF grant info, but this hasn't appeared on the server yet.  

This means there is only one more thing to do to close this ticket: fix the "You can also e-mail us at ----" statement in the how-to-get-involved question on the FAQ.  I would suggest to just link to phylotastic.org/about.html#participate .  That is, just change the words to "To learn more about how to participate, see http://www.phylotastic.org/about.html#participate".   That way we will only have to maintain the information in one place, rather than in duplicate.

**Comment by ducvan0212** [comment]
I replaced "You can also email us at ----" with "To learn more about how to participate, see http://www.phylotastic.org/about.html#participate". But I could not open  http://www.phylotastic.org/about.html#participate.
Anyway, I love the idea of putting all contact information into a single place.

**Comment by arlin** [comment]
Thanks.  Yes, the #participate anchor is not on the web server at present, but it will be pulled when the server is updated (see git repo phylotastic.github.io/about.html).   I think @epontell is the webmaster.  The #participate anchor points to this: 

<img width="587" alt="screen shot 2016-09-16 at 2 13 59 pm" src="https://cloud.githubusercontent.com/assets/1659198/18596590/e6c42982-7c17-11e6-9396-fc280b05db13.png">
