### ISSUE TITLE
Authentication is unwelcoming and confusing

### ISSUE THREAD

**Issue by hlapp** [phylotastic/phylotastic-portal#144]
* [ ] The homepage first greets one with a red background error message (“You need to sign in or sign up before continuing”). That’s bad form (because telling people that they’ve done something wrong before they’ve done anything at all is like saying they’re not welcome), and it’s made worse by not saying anything about why one would need to sign in.
* [x] The Google Auth icon is for Google+, not Google Auth, which makes a user wonder why they should be signing into Google Plus (which has ones personal network).

**Comment by ducvan0212** [comment]
I changed login page like this

<img width="415" alt="screen shot 2016-09-12 at 5 53 55 pm" src="https://cloud.githubusercontent.com/assets/1614884/18456927/11b0abe2-7912-11e6-9e80-aef02611208c.png">

**Comment by hlapp** [comment]
@ducvan0212 I'm sorry but that doesn't address it. It still uses the Google Plus icon, even though you aren't asking the user to sign into their Google Plus network. Why not use an icon that isn't misleading, such as the [Google FontAwesome icon](http://fontawesome.io/icon/google/).

**Comment by ducvan0212** [comment]
<img width="511" alt="screen shot 2016-09-13 at 8 50 31 am" src="https://cloud.githubusercontent.com/assets/1614884/18478660/48515976-798f-11e6-8cf2-4ca0ce8cf186.png">

I updated Font Awesome icon.

Thank you for correcting me.

**Comment by ducvan0212** [comment]
I am refactoring code in home page so that user dooesn't need to sign in to see public lists. In list API, the getting a specific public list (https://github.com/phylotastic/phylo_services_docs/blob/master/SpeciesListServer/SpeciesListServicesDescription.md#web-service-10) requires user identification which can not be retrieved. Can @abusalehmdtayeen modify the service?

**Comment by bomeara** [comment]
FWIW, I agree with @hlapp completely on this: **nothing** we do should require login by default -- only for things where a user might want to opt in for privacy (like private lists), though I could see a strong argument against even that (however, some researchers might want to use our services without "tipping their hand" for their great unpublished work). The one exception might be student data, but handling student names, etc. is legally involved (google FERPA).

**Comment by ducvan0212** [comment]
I also totally agree on this. For now, you can access the home page without any permission and the published list is not shown up because our DCA species list services requires user identities to all operations so I am asking @abusalehmdtayeen to make some changes. However, accessing further (create, edit, update, destroy actions for any objects) requires signing in/signing up.

**Comment by arlin** [comment]
thanks @ducvan0212 .  I'm closing this.
