### ISSUE TITLE
"Not solanum" bug

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#147]
1.  Attempt to create list of 6 species from https://github.com/phylotastic/phylotastic/blob/master/test_data/miscellaneous/six_plants_from_RW.txt

2.  Look at taxon match report. There are 7 species.   Solanum tuberosum appears to match twice, items 4 and 5.  In the taxon report, one of the species is literally "not Solanum tuberosum", but the list view doesn't show us which one.  Both matches look the same.    

*We want to eliminate this species.*  

3.  Click "Edit list".  Too bad.  This only allows you to edit the list name, not the list.  

So, we give up on trying to edit the list.  We will just deselect one of the names and get a tree.  We don't know whether to deselect 4 or 5, so we will try each one below.  

4.  Deselect item 4.  Choose "Get tree".  Fail: the tree has all 7 species.  

5.  Try again.  Deselect item 5.  Choose "Get tree".  Fail: the tree has only 5 species, with no Solanum.  

There are multiple problems with this behavior.  
* we are retaining 2 matches to one input name
* we are retaining a match to an input name that is literally "not Genus species"
* the list edit function does not work
* the list view interface does not distinguish the two matches, therefore we don't know which one to de-select
* the de-select function appears to work inconsistently, removing either 0 or 2 species instead of 1.

**Comment by ducvan0212** [comment]
- Retaining 2 matches to one input name: we had a ticket for this issue #84 . In portal, I just display result of calling the service so removing duplicate names from portal side is just a short-term fix.
- retaining a match to an input name that is literally "not Genus species": This seems to be a special case. Can @abusalehmdtayeen contact service creators to clarify what we should do? 
- List function does not work: In initial portal design version 2, there is no specification for edit list. In #120, @hdliv claimed that he wanted to change name of a list and in #97, he also wanted to edit public attribute of a list that extracted from DCA document. So I created the "Edit list" popup to do the tasks hdliv assigned to me. I will implement edit species of list as your request.
- the list view interface does not distinguish the two matches: @arlin Do you think displaying "synonym" column in tree viewer can address this problem?
- the de-select function appears to work inconsistently, removing either 0 or 2 species instead of 1: Getting tree service accepts names of species as input so there will be no difference between no species and either species is removed. In other words, "Solanum lycopersicum" is still in getting tree request if removing either names. But removing 2 names eliminates "Solanum lycopersicum" in getting tree request.

**Comment by abusalehmdtayeen** [comment]
@ducvan0212 @arlin , I think (we are retaining 2 matches to one input name) this issue is now resolved since I have implemented the feature to remove duplicates from the names list. Can you check whether it is working now?

**Comment by arlin** [comment]
This bug has been fixed at the OT end, so closing this.
