### ISSUE TITLE
Large trees generated but not displayed

### ISSUE THREAD

**Issue by hdliv** [phylotastic/phylotastic-portal#283]
Large trees (more than 4600):  the tree image is generated but not displayed

**Comment by hdliv** [comment]
@abusalehmdtayeen should I move this to 'in progress'?

**Comment by hdliv** [comment]
Hi Abu.  I sent the lists to view on gitter

**Comment by abusalehmdtayeen** [comment]
@hdliv , the main reason of not displaying the tree is that the tree image generated by ETE is too large to be shown in a browser. Usually if the number of taxons in a list is more than 1000 the image file size exceeds 3 MB. I think it is better if we restrict the users to use lists with maximum size 1000.

**Comment by hdliv** [comment]
@abusalehmdtayeen I agree with the restriction to 1000.  what about you @arlin ?  moving to in review

**Comment by arlin** [comment]
yes, this should be closed, but we need to implement #266.  This includes 1. detecting size of request, 2. imposing limits and 3. informing the user what is happening and what the limits are (so that the user is not confused).  if there is any question about how to implement this @ducvan0212, please ask in the thread for #266
