### ISSUE TITLE
selecting species table in tree getter view

### ISSUE THREAD

**Issue by ducvan0212** [phylotastic/phylotastic-portal#29]
After extracting, users are allowed to choose which species will be included in tree.

**Comment by hdliv** [comment]
with 8 tests, the web portal extraction is returning unsucessfully-resolved and unsucessfully-extracted for .pdfs and urls.  .doc are resolve but there are no taxa in the prune tree

**Comment by arlin** [comment]
Name extraction frequently fails.  When the name-selecting table appears, it allows me to select names (including select all and unselect all).  However, I do not know if the selection actually works because I have not yet seen the effect on the downstream tree.  Please provide an example that is guaranteed to work so that we can test whether name-selection is effective.

**Comment by arlin** [comment]
OK,  I created two simple text files in phylotastic-portal/examples, one with names for eleven plant species, and the other with names for 30 pet species.  

With these I have verified that name selection works.   Thanks.  This is a good feature.  I wonder if we could combine it with the taxon match report?

**Comment by ducvan0212** [comment]
I totally agree to integrate name selection to taxon matching report.
