### ISSUE TITLE
intermittent bug when name of list is missing

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#310]
This may be induced by some of the problems.  

The dialog box for uploading a list or extracting a list no longer requires a name.  Sometimes, a list is created and it is given the name of the input file.  However, sometimes the list is processed but it does not appear in the menu.  

I cannot get this bug to work consistently.

**Comment by ducvan0212** [comment]
The name of the list is not required. If the list name is not given by user, the portal will take name of file or the url for name of the list. Users can edit the list name if they want.

The portal will create the list once the service returns results. If the portal can not reach the service for example, the list will not be created.

**Comment by arlin** [comment]
This is not what is happening.  Sometimes I see the transient green status message that says the list has been created, but there is no item in the user list menu. I will try to capture that but it disappears pretty quickly.

**Comment by ducvan0212** [comment]
I think the same problem with token saved in cookies. The dev uses token1 to identify session of user1. When you switch to production, the token1 is replaced by token2, then you are identified as user2 in production. You then lost token1 in dev. The portal dev will need to reassign you a new token because token2 can not be used in dev.

**Comment by arlin** [comment]
OK, I was not able to recreate the problem when using separate sessions (browsers) for dev and production.  So, closing this.
