### ISSUE TITLE
Matching multiple taxonomies fails

### ISSUE THREAD

**Issue by bomeara** [phylotastic/phylotastic-portal#344]
I entered formicidae of the US in the get list function. 

I get this screen:

![screen shot 2018-12-28 at 10 25 50 pm](https://user-images.githubusercontent.com/1612612/50533004-dfd12d00-0aef-11e9-9689-6c4155b56aaa.jpg)

Clicking on select generates:

![screen shot 2018-12-28 at 10 28 47 pm](https://user-images.githubusercontent.com/1612612/50533014-f8414780-0aef-11e9-9f24-009616246d83.jpg)

**Comment by ducvan0212** [comment]
Brian, you can only select one subset method. 

<img width="878" alt="screen shot 2018-12-29 at 11 05 52 am" src="https://user-images.githubusercontent.com/1614884/50533355-83572780-0b5a-11e9-9948-cff4e564cb48.png">

I guess you selected both subsetting by country and by popularity for taxon "formicidae". For avoiding confusion like yours, I updated the interface, so that you can only tick on one checkbox.
