### ISSUE TITLE
tree construction with taxon

### ISSUE THREAD

**Issue by ducvan0212** [phylotastic/phylotastic-portal#39]
Works but not complete in popularity species selection because of lack of database

**Comment by arlin** [comment]
I'm not seeing this.  All I get is "Sorry! Service is unavailable. We will fix it soon."

I added a separate ticket to set up the popularity database.  We need to coordinate that with other groups.

**Comment by arlin** [comment]
OK, I learned last Thursday that one has to select the "I want to use all of found species in that taxon" option.  However, I cannot get this to work.  I am using the taxon "Felidae" (cat family, including lions, tigers, bobcats, etc).  I can get a list of species, but the tree is always empty.  This is probably because the list is (for some strange reason) only extinct species.  I will post this as a bug to the web services repo.

**Comment by arlin** [comment]
I was able to get this to work with Panthera or Felis, which are genera within the family Felidae.
