### ISSUE TITLE
embedded viewer frame bug

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#44]
Extract names from examples/thirty_pet_species.txt, select all, get tree.  Expand all of the collapsed nodes.  The viewer does not have enough space, and the right side of the tree gets cut off.  This does not have to do with the width of the browser window.  

If you can't reproduce this, I will send an image.  

I suspect that this bug was induced when the decision was made to provide an initial view with all nodes collapsed.  The initial tree is small.  I think the embedded viewer cannot estimate how much space it will need when the tree is expanded, and it cannot resize dynamically.

**Comment by ducvan0212** [comment]
I kept aware of that issue. It is not a bug anyway. I fixed width and height of displaying area. Making space for interaction with tree dynamically change needs a lot more time and work so lets keep this issue on track. Thanks.

**Comment by ducvan0212** [comment]
Ok, I made the tree viewer scale both width and height automatically whenever there is an expansion in number of nodes in graph. Following expansion of width may be sometimes more "comfortable" than following expansion of height because it is impossible to direct screen of user follow the movement of nodes. For instance, you open a parent node which has 1000 children node then your screen will stay in the same position but the context of nodes around you is changed so it will create a "strange" effect from user perspective.

It is available in server. Thats for now.

**Comment by arlin** [comment]
Yes, this works now.

**Comment by arlin** [comment]
this is a small thing, so I'm going to move it directly to done, OK?
