### ISSUE TITLE
list of examples is empty

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#68]
When the user goes to the pre-bullt lists workflow, we want them to see a list of examples that they can choose from.  Currently the list is empty.  

![screen shot 2016-04-14 at 3 11 40 pm](https://cloud.githubusercontent.com/assets/1659198/14540497/4f2f3b22-0253-11e6-9ea2-f92921f81417.png)

**Comment by hdliv** [comment]
+1 @arlin that started yesterday in the afternoon, since I was able to test and then afterwards I saw the same problem

**Comment by ducvan0212** [comment]
For now, portal is very sensitive with any change in Abu species service. Abu made some changes and I have to fix conflicts in data first. I can bypass that error but I am not sure ignoring the error in development is a good choice.

@abusalehmdtayeen Is there any way to update species list information in portal automatically when you make some changes in your service? Everytime I checked, the problem was from public lists. Because I keep information about which lists user uploaded, which public list was used to create a tree by which (other) users so if you change data in your service and portal database is not updated, then there will be conflicts. For instance, the nearest error is when public list id are 1, 2, 3, 4, 5, 7 and in the portal, there are only list id 1, 2, 3, 4, 5, 6. When Prof. Arlin wanted to create list from list id 7, portal can not find information about list id 7 in its database despite that the list 7 can be seen from web interface, thus error is displayed. Currently, there are 8 public lists received from the service but only 5 in portal database. That means there are 3 lists not coming from the portal. In other words, the data in portal and service have to be consistent. 

I am thinking about doing a database reset in portal so maybe Prof. Arlin and Dail will have to recreate your username. If I do, I will notify you.

**Comment by arlin** [comment]
@ducvan0212 , I would suggest to think about the design of this interaction differently.  The portal presents the user with any available public lists.  This can be supplied by querying the list server.  When the user selects a list, and the portal acquires the content of the list, the portal must keep a copy of the data with its own internal ID.  This is a requirement because the user can edit the list inside the portal.  

Example.  List server has 2 public lists: pets = {cat, dog, ferret} and flowers = {violet, daisy, rose}.  Portal acquires lists and displays pets and flowers to user.  User chooses pets.  User adds "rabbit" to list, deletes "ferret".  User gets tree for cat, dog, rabbit.  Portal saves list {cat, dog, rabbit} with unique id for user.

**Comment by abusalehmdtayeen** [comment]
@ducvan0212 , When you reported that no public lists were found through the service, I checked the server database and found that there is no data about any lists. The only reason for that might be someone deleted those lists while testing the service APIs. So I imported the 7 lists that Dail sent me into the database again and thus the list ids changed.

**Comment by arlin** [comment]
This suggests that we need a separate production server where content will remain stable.
