### ISSUE TITLE
species service questions

### ISSUE THREAD

**Issue by ducvan0212** [phylotastic/phylotastic-portal#79]
Q1: I guess even when the system informed me that there was something error, a list is still created. After I tried to create 3 lists, there are errors which you indicate that all of attributes of a list have to be represent in creating request (eg, "{\"status_code\": 500, \"message\": \"Error parsing input json: KeyError-'list_description'\"}"
) but in the forth time, I succeed creating a list with returned id is 4. 

Personally, I think it is redundant to send a property that has value nil (null) when creating a list.

Q2: By list id, how can you determine that it is private or public? I have 2 solutions. The first one is checking list by list_id in portal database. What if the checked list is not in portal database => error as what Arlin and Dail encountered a couple days ago. To keep the portal function, I have to maintain the portal database so that every lists in species service are also available in the portal database.
The second is calling both private and public list getting request. But this solution is somehow expensive in term of request redundancy.

Q3: If you dont attach owner's email of a list, how can I determine who is the owner of the list? Solution is looking for the list in portal database but is the list record there? I am not sure.

Q4: Why does request of getting a public list only return names of species while request of getting a private list returns full information which is in different format. Specifically, for now, "list_species" can be an array of Hash or an array of String. For me, private or public list is well, list so I expect they are represented in the same format.

**Comment by abusalehmdtayeen** [comment]
@ducvan0212 
Ans. to Q1:
It was not actually creating a list when you got the error message. Just the list counter was being updated. It was a small bug and I fixed it.
Sending the properties with null values may be redundant, but we should actually follow a standard for the general users. Moreover, it is easier for you to create the json format using a standard. Because the CSV files contain all fields according to the standard. You just have to read the file and create the json format. You don't need to care about what values the user has put in the fields. This also allows the user to put empty values or "NA" values.

**Comment by abusalehmdtayeen** [comment]
@ducvan0212 :
Ans. to Q2:
If the list is public, just providing the list_id is enough. It will display the list. You can also use the verbose parameter to get all list properties and use the "is_list_public" property to know whether the list is public or not. If the list is not public, just providing the list_id will give you a message saying that the list is private. Only valid users can access their private lists. To access a private list, you need to provide the service API with the user_id and access_token in addition to the list_id.

I don't understand why you want to save every list information in the portal database. Its already stored in the species list server database. Using another database to save the same information will again create conflicts. Your job is to track which user has logged in to your portal, create access token for him, relay the request of the user to the appropriate service API and display the result returned by the service. That's it. 

Let me give you an example. When a user logs in and go to the pre-built list page you can immediately send a request to my get_list service API with the user_id and access_token. The service will return you all the lists (public/private) of that user. You then display the returned information in a organized way to the user. If you want you can save the information temporarily in memory or in a database. If the user makes any request to update or view any specific list, you have to send another request to the appropriate service API to complete user's action. Everything is maintained in the species list server database. So when the user logs out you don't have to worry about saving the actions. Because when user logs in again, you redo the same procedure and the service API will give you the updated result.

**Comment by abusalehmdtayeen** [comment]
Though public lists are for all users, it is still associated to a particular user who owns the list and only he can change or remove the list using his user_id and access_token. That's how the service API is designed according to the discussion we had in our last meeting.  Now anyone can view all the lists publicly available by using the get_list service API without any parameter. And the users will only care about the content of the lists, not the owners of the list. Again, you don't need to save the public list information in the portal database, so you don't need the owners. 

Same type of example applies to this case too. When the user logs in, you send a request to the get_list API to retrieve all the public lists and display the result to the users. Now if the user who has logged in has some public lists of his own, it will appear in both public and private sections of your interface. And he can modify any list (public/private) if he is the owner. So you call the appropriate service APIs based on user's actions. The species list server will maintain every update a user makes. So there is nothing to save in your end.

**Comment by abusalehmdtayeen** [comment]
@ducvan0212 :
Ans. to Q4:
Yes, you are right. Both public and private lists should be represented in the same format. I have not noticed it. I will check. If it is different, I will fix it to display in the same format.

**Comment by ducvan0212** [comment]
Q1: It is no problem to me to insert nil field into body of request. I just think it is not a convention. Anyway, it is okay with question 1.

Q2: So to determine a list is public or private, your solution is sending a request to public list to test whether or not your list_id is public. After that, if response indicates that your list is not public, you will send a request to private list endpoint. For example, I give you list id 4. You call to public list service and you succeed! => You said it is public list => The current user who is logged in and having a session in portal dont have privilege to modify list. What if I tell you list_id 4 is mine? That means your inference is wrong and in order to make it right, I have to ALWAYS call 2 requests to public and private list service and compare the response to just know that a list is public or not. You may wonder why public or private property is important to me, it is because the portal have to display actions for users depending on the property of the list.
Do you think about combining public and private list endpoint and require me to include user email and access token every time I call the service? Your service will check ownership of the list and compare with the credentials I provided. (*)

The main reason I want to keep track of list_id in portal database is I want to know the source of the tree. I agree that building a tree from a list is trivial but given a tree, how can you said which list it belongs to? 
@arlin: Would you please enlighten Abu and me about the idea of source of tree? Is it necessary to display list information from which the tree is constructed when displaying the tree?

Q3: Let say you have public list [1, 2, .. ,1000] with no information about ownership. You want to modify list 1 but you can not prove you are the owner of list 1. In other words, I know you logged in to portal, know your identity, know your credentials but I dont know who is the owner of the list. The only solution is calling a request to service (*) to check list ownership.

**Comment by abusalehmdtayeen** [comment]
@ducvan0212 : Lets have a short meeting to discuss the issues instead of just posting big questions and answers in waffle. I have the answers for you. I am available today from 3:30 pm to 5 pm in my office. Can you make it?

**Comment by ducvan0212** [comment]
OK. It is better to have face-to-face discussion.

**Comment by arlin** [comment]
@abusalehmdtayeen, regarding your response to Q3, I think we need to support the case in which the user1 wants to modify a public list of user2.   We want to encourage that kind of data re-use.  Here are some ways to solve the problem of what happens downstream when user1 specifies a public list that belongs to user2. 

* user1 attempts to edit the list, but the server refuses to accept the edits (current behavior?)
* portal keeps a temporary copy that user1 may edit, but changes get lost when a new session over-writes the list with user2's version 
* user1 clones the list and is required to provide a new name.  Now it is maintained as a separate list, whether public or private.

**Comment by ducvan0212** [comment]
Why do we need 2 separate service for adding and removing species of a list? I think both of them can be combine to only one service. It is more convenient, easier to implement when thinking about edit several species (each editing operation required one removing and one adding operation) and it is also more efficient in term of number of calling requests

**Comment by abusalehmdtayeen** [comment]
@ducvan0212 : Yes, you are right. Actually, I designed those two APIs thinking about the mobile app in the first version.  Later I combined those into the replace_species API. You can use that one.  I will disable these two APIs for now.

**Comment by ducvan0212** [comment]
I finished upgrading the portal. It will be take a little time to access "Jobs" page in the first time because I added some code to make sure the prebuilt list is on the database so please be patient. I am not sure there is any errors with current database so I will do a database reset, but only after @abusalehmdtayeen reset the list service. However, please wait for @hdliv to have a look at what I did because I want to see how my code works with current database.
