### ISSUE TITLE
date format

### ISSUE THREAD

**Issue by ducvan0212** [phylotastic/phylotastic-portal#83]
I saw @arlin uploaded Top20 file and in that file, the date field is "4/14/16"

This date is invalid. 
=> "4/14/16"
[4] pry(#<ListProcessingWorker>)> s.to_date
ArgumentError: invalid date

So can we formalize the date?

**Comment by hdliv** [comment]
@arlin @ducvan0212 
As we can possibly (hopefully) have people outside of USA adding data and the US is the only country that uses the weird MM-DD-YYYY where the world uses DD-MM-YYYY .. I advocate for the use of the ISO-8601 international standard format: 
YYYY-MM-DD.  
Thus, March 30, 1998 would be: 1998-03-30.

**Comment by arlin** [comment]
specify the format that is acceptable, then put that in the documentation.

**Comment by hdliv** [comment]
If it Ok with someone.  We will use the ISO international format. Is it OK with all?    YYYY-MM-DD

**Comment by hdliv** [comment]
@abusalehmdtayeen I Abu.  I just wanted to put you in the conversation as well

**Comment by hdliv** [comment]
@arlin @abusalehmdtayeen The date format has been changed in the documentation.

**Comment by abusalehmdtayeen** [comment]
@hdliv : I have to change in my end to accept the new date format. I think Van has to change as well.

**Comment by arlin** [comment]
@abusalehmdtayeen, I don't think @ducvan0212 needs to change anything because he is just transforming csv into json, probably without testing content.    Changing the date format means that we need to delete or fix all the current lists, right?   When you are ready to make this change, it might be a good time to erase all the content on the list server and start again.

**Comment by abusalehmdtayeen** [comment]
Ok, After I make changes in my end, I will reset the database and let Van know.

**Comment by hdliv** [comment]
@abusalehmdtayeen thank you

**Comment by abusalehmdtayeen** [comment]
ISO standard date formats are now allowed in species list database.

**Comment by ducvan0212** [comment]
@abusalehmdtayeen do I need to parse (verify) the date in my end before sending to you?

**Comment by abusalehmdtayeen** [comment]
@ducvan0212 : Yes, please make a small check to see if every date is in 'YYYY-MM-DD' format while reading the CSV files. If it is in correct format then send me the request, otherwise, just show a message to the user to correct the date format. Also remember that I allow users to put "NA" values in case they do not want to put the date values.  So you can make a check for the format only if a date value exists in the corresponding column.

**Comment by ducvan0212** [comment]
Already implemented in the server but @abusalehmdtayeen did a reset too soon :). If I test then you will have to reset your service again. @hdliv please test this with your lists and let me know if there is error.

**Comment by arlin** [comment]
I have tested this with 3 lists using YYYY-MM-DD format, and it works fine.  Thanks!  

Also, this seems to happen instantly, whereas previously there was a noticeable delay.
