### ISSUE TITLE
user_id does not exist in service

### ISSUE THREAD

**Issue by ducvan0212** [phylotastic/phylotastic-portal#85]
The problem when @arlin clicked to see public list is his email is not in the service database. He should be allowed to see a public list even when he does not have any lists in the service

**Comment by abusalehmdtayeen** [comment]
@ducvan0212 : I have fixed the issue. Can you check again now?

**Comment by ducvan0212** [comment]
Hmm, I dont have another gmail. Let see if this prob is solved after the database reset

**Comment by abusalehmdtayeen** [comment]
@ducvan0212 : I tested it using the service API with my email. Since I don't have any list on the server, I should be able to access the public lists. And the the service API displays result for list_id 12 in my case. But I tried to use your portal with the same list, it showed me permission denied. Can you please check your end?

**Comment by ducvan0212** [comment]
I fixed. Would you please take a look?

**Comment by abusalehmdtayeen** [comment]
Thanks @ducvan0212. It works now. +1
